### ISSUE TITLE
Bulding the pdf failed 

### ISSUE THREAD

**Issue by theonov13** [f-fathurrahman/ImplementingDFT#1]
Hi, 

I really like the idea of this book. 
Sadly, at least for me, the current build script does not correctly build the pdf. 
I found in the git history this pdf version 

https://github.com/f-fathurrahman/ImplementingDFT/blob/83375707a12382e1d1127d1ec41978cad5b5b218/book/ImplementingDFT.pdf

I guess it would be nice if a pdf version of the current version would be liked at the front of README.md 
```
[Current PDF version v.X.Y.Z](local_path_at_git)
``` 

What are your plans for finishing the book? 
As long as it is an unfinished stage it would be really nice 
to have a way to cite your work at least semi-correctly, 
may the simplest solution would be to like the current repo 
to https://zenodo.org/. 

Thank you for all your work!

Best, 
Sebastian

**Comment by f-fathurrahman** [comment]
Hi,

I'm sorry that I didn't put the information about building the pdf for the book. To build the book you need the following:

- Lualatex: This is needed for accessing system font's. In this case the font is JuliaMono which contains many Unicode symbols. This can be changed to other fonts that support Unicode such as DejaVu Mono.

- minted Latex package and its requirement, especially Python and Pygment syntax highlighter.

I will try to include the most recent pdf in the repo for convenience.

> What are your plans for finishing the book?
> As long as it is an unfinished stage it would be really nice
> to have a way to cite your work at least semi-correctly,
> may the simplest solution would be to like the current repo
> to https://zenodo.org/.

I am afraid that there is still a long way to go before finishing the book. I also intend to include parallelism via MPI and PETSc. Unfortunately, there are no stable Julia wrapper's for PETSc, so we might end up writing our own solution. I will also discuss with my co-author about setting up Zenodo reference. For the time being, the material in this book can be used freely without attribution.

I'm also pushing some modifications in the code. It is now using sparse vectors for non-local pseudopotential operator, hopefully this can speed up the calculations.

PS. Sorry if I'm asking you outside the topic. Are you currently trying to implement FLOSIC method for extended systems? I'm very excited to see the application of this method!

**Comment by theonov13** [comment]
Hi, 

my OS says I have installed everything needed. 
I tried to run 

```
bash build.sh 
```  

and get errors like 

``` 
! Package luatex.def Error: File `../codes/FD1d/IMG_gaussian_1d_8pt.pdf' not fo
und: using draft setting.
```  

An up-to-date pdf file would be nice, thank you in advance. 

It looks like that the pictures are actually not there. 
Do I need to produce the picture while running the codes?
Or are the pictures supposed to be in the respective places? 

This sounds really interesting. I never heard about PETSc before and need to google it first. 
Let me know if there will be any update Zenodo or some other way to reference your book. 

I already have some FLO-SIC implementation for model extended systems, 
which is simple-minded and non-useable at all. 
Our current focus is the reproducibility of SIC results. 

I'm currently facing the standard problem, 
giving a student a programming task, 
implementing something new on top of something existing
within a limited amount of time, 
turns out to be an impossible challenge. 

Therefore I throw-away everything and started from "ab-initio" 
and try to figure out the best practice for implementing DFT
and beyond methods. If you want to know more, 
we might discuss this by mail?

**Comment by f-fathurrahman** [comment]
> and get errors like
>
>  ! Package luatex.def Error: File `../codes/FD1d/IMG_gaussian_1d_8pt.pdf' not fo
>  und: using draft setting.

I'm sorry for this. The pictures are actually will be generated by running the Julia programs in several directory. They are often updated and I exclude them from the repo.
I have include the pdf build in the repository now. It is under the repository directory. It is still far from complete, unfortunately.

> Therefore I throw-away everything and started from "ab-initio"
> and try to figure out the best practice for implementing DFT
> and beyond methods. If you want to know more,
> we might discuss this by mail?

Sorry, if I derailed the discussion. If you don't mind, I will contact you via email and discuss more about SIC.

**Comment by theonov13** [comment]
No problem. Only people working hard make errors. And only from errors, we can learn how to make things better.
While not complete it is still the 2nd best summary for a DFT implementation after Prof. Tomás Arias DFT++ mini-course lectures I have ever seen. Let me know if you like to have comments,  suggestions, or text fragments for missing/incomplete sections. 
I would assume many students can profit at an early stage of computational/theoretical physics/chemistry from your work. 

Thank you for adding the pdf file. 

Don't hesitate to ask any questions.
You may email me at my official email address

sebastian.schwalbe@physik.tu-freiberg.de

because this is the one I need to read on a regular basis.
